language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "pypy3.5"   
# command to install dependencies
install:
  - pip install -r Players/requirements.txt
# command to run tests
script:
  - pytest # or py.test for Python versions 3.5 and below
